schema_version = "1.0.0"
id = "io_import_pixelart"
version = "1.2.0"
name = "Import Pixel Art"
tagline = "Imports pixel art as colored cubes or squares for each pixel"
maintainer = "Mathias Panzenböck"
type = "add-on"
tags = ["Import-Export"]
license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.2.0"

[permissions]
files = "Import pixel art from disk"

[build]
paths_exclude_pattern = [
    "/.git/",
    "/tmp/",
    "__pycache__/",
    "*.png",
    "*.zip",
    ".*",
]
